Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [27]:
import numpy as np

# function generate a Vander Matrix
# i_vec : vector, N: Number of Columns, increasing : Define order of powers   

def my_vander_Matrix(i_vec, N, increasing=False):

    if increasing:
        my_matrix = np.array([x**i for x in i_vec for i in range(N)]).reshape(i_vec.size,N)
    else:
        my_matrix = np.array([x**(N-1-i) for x in i_vec for i in range(N)]).reshape(i_vec.size,N)
    
    return my_matrix


input_Vector = np.array([1,2,3,4,5])
No_of_Column = 3
increasing = False

output_Matrix = my_vander_Matrix(input_Vector,No_of_Column,False)
print("Vander Matrix input_Vecotr: {0} No of column:{1} & increasing:{2}".format(input_Vector,No_of_Column,increasing))
print(output_Matrix)

increasing = True
output_Matrix = my_vander_Matrix(input_Vector,No_of_Column,True)
print("Vander Matrix input_Vecotr: {0} No of column:{1} & increasing:{2}".format(input_Vector,No_of_Column,increasing))
print(output_Matrix)

No_of_Column = 5
increasing = False

output_Matrix = my_vander_Matrix(input_Vector,No_of_Column,False)
print("Vander Matrix input_Vecotr: {0} No of column:{1} & increasing:{2}".format(input_Vector,No_of_Column,increasing))
print(output_Matrix)

increasing = True
output_Matrix = my_vander_Matrix(input_Vector,No_of_Column,True)
print("Vander Matrix input_Vecotr: {0} No of column:{1} & increasing:{2}".format(input_Vector,No_of_Column,increasing))
print(output_Matrix)


Vander Matrix input_Vecotr: [1 2 3 4 5] No of column:3 & increasing:False
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Vander Matrix input_Vecotr: [1 2 3 4 5] No of column:3 & increasing:True
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
Vander Matrix input_Vecotr: [1 2 3 4 5] No of column:5 & increasing:False
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Vander Matrix input_Vecotr: [1 2 3 4 5] No of column:5 & increasing:True
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [26]:
# function generate a moving average sequence
# i_Sequence : Input sequence, 
# window_size: window size k>0, the k-th moving average of the input sequence   

def moving_avg_sequence(i_Sequence, window_size=0):
    try :
        if window_size > 0:

            row = i_Sequence.size - window_size + 1 #  moving average sequence total values   
            my_matrix = np.array([i_Sequence[i+x] for x in range(row) for i in range(window_size)]).reshape(row,window_size)
            out_moving_avg_sequence = np.sum(my_matrix,axis = 1)/window_size
            return out_moving_avg_sequence
        else:
            print("Window size must be zero!")
    
    except :
         print("Unexpected error:", sys.exc_info()[0])

            
my_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size = 3
print("Input array: {0} window size :{1}".format(my_array,window_size))
print("Moving average :")

print(moving_avg_sequence(my_array,window_size))

    

Input array: [  3   5   7   2   8  10  11  65  72  81  99 100 150] window size :3
Moving average :
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
